# This job is used to stop Helm from managing resources without deleting them.
apiVersion: batch/v1
kind: Job
metadata:
  name: kotsadm-keep-resources
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          # Delete old abandon-resources job if it exists
          kubectl delete job kotsadm-abandon-resources -n {{ .Release.Namespace }} --ignore-not-found

          # Annotate resources to keep them
          if kubectl get configmap kotsadm-confg -n {{ .Release.Namespace }} -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' | grep -q "Helm"; then
            kubectl annotate configmap kotsadm-confg -n {{ .Release.Namespace }} helm.sh/resource-policy=keep
          fi
          if kubectl get configmap kotsadm-application-metadata -n {{ .Release.Namespace }} -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' | grep -q "Helm"; then
            kubectl annotate configmap kotsadm-application-metadata -n {{ .Release.Namespace }} helm.sh/resource-policy=keep
          fi
          {{- if .Values.passwordSecretRef }}
          if kubectl get secret kotsadm-password -n {{ .Release.Namespace }} -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' | grep -q "Helm"; then
            kubectl annotate secret kotsadm-password -n {{ .Release.Namespace }} helm.sh/resource-policy=keep
          fi
          {{- end }}
        image: {{ .Values.images.kotsadm }}
        imagePullPolicy: IfNotPresent
        name: keep-resources
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: OnFailure
      serviceAccountName: kotsadm
