{{ if not .Values.kurlProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: admin-console
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
{{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
    nodePort: {{ .Values.service.nodePort }}
{{- end}}
  selector:
    app: kotsadm
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
{{ end }}
