apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: kotsadm
  type: ClusterIP
