{{- $kotsadmSts := lookup "apps/v1" "StatefulSet" .Release.Namespace "kotsadm" }}
{{- if $kotsadmSts }}
# if kotsadm statefulset exists, we need to migrate the data to rqlite
apiVersion: batch/v1
kind: Job
metadata:
  name: kotsadm-migrate-pvc-to-rqlite
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "1"
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          kubectl scale sts/kotsadm -n {{ .Release.Namespace }} --replicas=0
          kubectl wait --for=delete pod --selector=app=kotsadm -n {{ .Release.Namespace }} --timeout=300s
        image: {{ .Values.images.kotsadm }}
        imagePullPolicy: IfNotPresent
        name: scale-down-kotsadm
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      containers:
      - command:
        - /kotsadm
        - migrate
        - pvc-to-rqlite
        env:
        - name: RQLITE_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: kotsadm-rqlite
        image: {{ .Values.images.kotsadm }}
        imagePullPolicy: IfNotPresent
        name: migrate-pvc-to-rqlite
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /kotsadmdata
          name: kotsadmdata
      restartPolicy: OnFailure
      serviceAccountName: kotsadm
      volumes:
      - persistentVolumeClaim:
          claimName: kotsadmdata-kotsadm-0
        name: kotsadmdata
{{- end }}
