apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-minio
spec:
  selector:
    matchLabels:
      app: kotsadm-minio
  serviceName: ""
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: kotsadm-minio,minio-config-dir,minio-cert-dir
      labels:
        app: kotsadm-minio
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -C /home/minio/.minio/ --quiet server
          /export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: kotsadm-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: kotsadm-minio
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_UPDATE
          value: "off"
        image: {{ .Values.adminConsole.images.minio }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: kotsadm-minio
        ports:
        - containerPort: 9000
          name: service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /export
          name: kotsadm-minio
        - mountPath: /home/minio/.minio/
          name: minio-config-dir
        - mountPath: /.minio/
          name: minio-cert-dir
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
        - 1001
      volumes:
      - name: kotsadm-minio
        persistentVolumeClaim:
          claimName: kotsadm-minio
      - emptyDir: {}
        name: minio-config-dir
      - emptyDir: {}
        name: minio-cert-dir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        {{- include "admin-console.labels" . | nindent 8 }}
      name: kotsadm-minio
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
    status: {}