apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "kots-helm.labels" . | nindent 4 }}
  name: kotsadm-postgres
spec:
  selector:
    matchLabels:
      app: kotsadm-postgres
  serviceName: ""
  template:
    metadata:
      labels:
        app: kotsadm-postgres
        {{- include "kots-helm.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: kotsadm
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: kotsadm-postgres
        - name: POSTGRES_DB
          value: kotsadm
        image: postgres:10.18-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U kotsadm -h 127.0.0.1 -p 5432
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: kotsadm-postgres
        ports:
        - containerPort: 5432
          name: postgres
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U kotsadm -h 127.0.0.1 -p 5432
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kotsadm-postgres
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/run/postgresql
          name: run
        - mountPath: /etc/passwd
          name: etc-passwd
          subPath: passwd
      securityContext:
        fsGroup: 999
        runAsUser: 999
      volumes:
      - name: kotsadm-postgres
        persistentVolumeClaim:
          claimName: kotsadm-postgres
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: run
      - configMap:
          items:
          - key: passwd
            mode: 420
            path: passwd
          name: kotsadm-postgres
        name: etc-passwd
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      labels:
        {{- include "kots-helm.labels" . | nindent 8 }}
      name: kotsadm-postgres
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status: {}
status:
  replicas: 0