{{- $pvcSize := "5Gi" }}
{{- $rqliteSts := lookup "apps/v1" "StatefulSet" .Release.Namespace "kotsadm-rqlite" }}
{{- if $rqliteSts }}
{{- $pvcSize = (index $rqliteSts.spec.volumeClaimTemplates 0).spec.resources.requests.storage }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-rqlite
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.isHA | ternary 3 1 }}
  serviceName: kotsadm-rqlite-headless
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: kotsadm-rqlite
  volumeClaimTemplates:
  - metadata:
      name: kotsadm-rqlite
      labels:
        {{- include "admin-console.immutableLabels" . | nindent 8 }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ $pvcSize }}
  template:
    metadata:
      labels:
        app: kotsadm-rqlite
        {{- include "admin-console.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
      - name: authconfig
        secret:
          secretName: kotsadm-rqlite
          items:
          - key: authconfig.json
            path: authconfig.json
      affinity:
        {{- with .Values.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - kotsadm-rqlite
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.images.rqlite }}
        name: rqlite
        args:
        - -disco-mode=dns
        - -disco-config={"name":"kotsadm-rqlite-headless"}
        - -bootstrap-expect={{ .Values.isHA | ternary 3 1 }}
        - -auth=/auth/config.json
        - -join-as=kotsadm
        env:
        - name: GOGC
          value: "10"
        ports:
        - name: rqlite
          containerPort: 4001
        - name: raft
          containerPort: 4002
        volumeMounts:
        - name: kotsadm-rqlite
          mountPath: /rqlite/file
        - name: authconfig
          mountPath: /auth/config.json
          subPath: authconfig.json
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz?noleader
            port: rqlite
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 10
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz?sync&timeout=4s
            port: rqlite
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
