apiVersion: v1
kind: Service
metadata:
  name: kotsadm-rqlite
  labels:
    app: kotsadm-rqlite
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: rqlite
    port: 4001
    targetPort: rqlite
  selector:
    app: kotsadm-rqlite
---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm-rqlite-headless
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: kotsadm-rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: rqlite
