{{- $encryptionKey := randAlphaNum 24 | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-encryption") }}
{{- if $secret }}
{{- $encryptionKey = index $secret.data "encryptionKey" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-encryption
data:
  encryptionKey: {{ $encryptionKey }}

