{{- $pgPassword := uuidv4 }}
{{- $pgUri := printf "postgresql://kotsadm:%s@kotsadm-postgres/kotsadm?connect_timeout=10&sslmode=disable" $pgPassword }}
{{- $pgPasswordb64 := $pgPassword | b64enc | quote }}
{{- $pgUrib64 := $pgUri | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-postgres") }}
{{- if $secret }}
{{- $pgPasswordb64 = index $secret.data "password" }}
{{- $pgUrib64 = index $secret.data "uri" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "kots-helm.labels" . | nindent 4 }}
  name: kotsadm-postgres
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  password: {{ $pgPasswordb64 }}
  uri: {{ $pgUrib64 }}
