apiVersion: batch/v1
kind: Job
metadata:
  name: kotsadm-uninstall
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      serviceAccount: kotsadm
      containers:
          - name: delete-configmaps
            image: {{ .Values.images.kotsadm }}
            env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            command:
              - "/bin/sh"
              - "-ec"
              - "kubectl -n $NAMESPACE delete configmaps -l kots.io/kotsadm=true"
          - name: delete-secrets
            image: {{ .Values.images.kotsadm }}
            env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            command:
              - "/bin/sh"
              - "-ec"
              - "kubectl -n $NAMESPACE delete secrets -l kots.io/kotsadm=true"
