apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: embedded-cluster-kotsadm-support-bundle
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
    troubleshoot.io/kind: support-bundle
spec:
  # NOTE: This is commented out until we have a decision on how to handle this with custom domains.
  # uri: https://raw.githubusercontent.com/replicatedhq/kots-helm/main/troubleshoot/embedded-cluster-support-bundle.yaml
  collectors:
  - clusterResources:
      namespaces:
      - _NAMESPACE_
  - logs:
      name: podlogs/kotsadm
      selector:
      - app=kotsadm
      limits:
        maxAge: 720h
  - logs:
      name: podlogs/kotsadm-minio
      selector:
      - app=kotsadm-minio
      limits:
        maxAge: 720h
  - logs:
      name: podlogs/kotsadm-rqlite
      selector:
      - app=kotsadm-rqlite
      limits:
        maxAge: 720h
  - logs:
      name: podlogs/kurl-proxy-kotsadm
      selector:
      - app=kurl-proxy-kotsadm
      limits:
        maxAge: 720h
